domain: "activity_recognition"
test_ids:
  - OND.0.90001.2100554
dataset_root: ""
save_dir: GAE-features
feature_extraction_only: True
save_features: True
seed: 2194
algorithms:
  gae_nd:
    smqtk:
      class: gae_nd
      config:
        feature_extractor_params:
          backbone_weight_path: ""
          name: "i3d"
          arch: "i3d-50"
          graph_weight_path: ""
          model_name: "i3d"
          n_classes: 400
          no_cuda: False
          hidden_dims:
            - 512
            - 128
          hidden: True
          in_dim: 1024
          num_heads:
            - 4
            - 1
          sample_duration: 64
          mode: "feature"
          graph_classes: 88
          feature_type: "3d"
        evm_params:
          weight_path:  ""
          number_of_unknown_to_crate_evm: 7
        characterization_params:
          clustering_type: "FINCH"
          number_of_unknown_to_strat_clustering: 50
        dataloader_params:
          sample_size: 224
          mean:
            - 114.7748
            - 107.7354
            - 99.475
          sample_duration: 64
          batch_size: 1
          n_threads: 6
          n_classes: 88
        csv_folder: "activity_recognition"
        cores: 6
        detection_threshold: 0.5
harness:
  smqtk:
    class: ParHarness
    config:
      url: ""
