domain: transcripts
dataset_root: ''
test_ids:
  - OND.0.10001.3518340
algorithms:
  HWRNoveltyDetector:
    smqtk:
      class: HWRNoveltyDetector
      config:
        config_file_path: "m18_hwr_config.yaml"
        cores: 1
        device: gpu
        img_height: 64
        hogs_ppc: 16
        unknown_threshold: 0.5
        detection_scalar: 0.5015
        crnn_pass: []
        save_header_csv: 0
        gpu_index: 0
        csv_folder: "writer_identifier"
harness:
  smqtk:
    class: ParHarness
    config:
      url: 'http://3.32.8.161:5000/'
