domain: "image_classification"
test_ids:
  - CONDDA.2.1.293
dataset_root: ""
hints:
  - "red_light"
save_dir: image_classification
seed: 2194
algorithms:
  CONDDA_5_14_A1:
    smqtk:
      class: CONDDA_5_14_A1
      config:
        efficientnet_params:
          model_path: ""
          known_classes: 413
        evm_params:
          model_path: ""
          known_feature_path: ""
          tailsize: 33998
          cover_threshold: 0.7
          distance_multiplier: 0.55
          number_of_unknown_to_crate_evm: 3
        characterization_param:
          clustering_type: "FINCH"
          number_of_unknown_to_strat_clustering: 20
        dataloader_params:
          batch_size: 128
          num_workers: 8
        csv_folder: "image_classification"
        cores: 6
        detection_threshold: 0.3
harness:
  smqtk:
    class: ParHarness
    config:
      url: ""
