domain: "image_classification"
test_ids:
  - OND.54012315.0900.1239
dataset_root: ""
use_feedback: True
has_reaction_baseline: False
has_baseline: False
save_dir: image_classification
seed: 2194
save_attributes: True
save_elementwise: True
saved_attributes:
  FeatureExtraction:
    - "FVs"
    - "image_names"
    - "Pr"
    - "P_max_known"
skip_stages:
  - "WorldDetection"
  - "NoveltyClassification"
  - "NoveltyAdaption"
  - "NoveltyCharacterization"
algorithms:
  OND_12_Without_Redlight:
    smqtk:
      class: OND_12_Without_Redlight
      config:
        efficientnet_params:
          model_path: ""
          known_classes: 413
          image_size: 300
        evm_params:
          model_path: ""
          tailsize: 40000
          cover_threshold: 0.7
          distance_multiplier: 0.55
          distance_function: "cosine"
          mu_train: 1.0
          sigma_train: 0.1872130436656377
          KL_threshold: 8.55648487230666
          known_threshold: 0.7
        feedback_params:
          first_budget: 10
          income_per_batch: 10
          maximum_budget: 10
        classification_params:
          alpha: 1.0
          flag_only_evm: 1
        dataloader_params:
          batch_size: 128
          num_workers: 8
        csv_folder: "image_classification"
        detection_threshold: 0.5
harness:
  smqtk:
    class: ParHarness
    config:
      url: ""
