defaults:
  -  base: base_ond
  -  override hydra/job_logging: colorlog
  -  override hydra/hydra_logging: colorlog
  -  _self_

hydra:
  output_subdir: config
  job_logging:
    colorlog:
      format: "[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s"
      log_color:
        DEBUG: purple
        INFO: green
        WARNING: yellow
        ERROR: red
        CRITICAL: red,bg_white
  hydra_logging:
      format: "[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s"
      log_color:
        DEBUG: purple
        INFO: green
        WARNING: yellow
        ERROR: red
        CRITICAL: red,bg_white
