name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7.10', '3.8.10', '3.9.5' ]
    name: build all repositories for python ${{ matrix.python-version }}
    steps:
      - name: Checkout sail on client
        uses: actions/checkout@v2
        with:
          path: sail-on-client
      - name: Checkout tinker engine
        uses: actions/checkout@v2
        with:
          repository: tinker-engine/tinker-engine
          path: tinker-engine
      - name: Checkout sail on api
        uses: actions/checkout@v2
        with:
          repository: darpa-sail-on/sail-on-api
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: Sail-On-API
      - name: Checkout sail on evaluate
        uses: actions/checkout@v2
        with:
          repository: darpa-sail-on/sail_on_evaluate
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: Sail_On_Evaluate
      - name: Checkout sail on tinker launcher
        uses: actions/checkout@v2
        with:
          repository: darpa-sail-on/sailon_tinker_launcher
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: sailon_tinker_launcher

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.local/share/poetry-virtualenvs
          version: 1.1.7

      - name: Capture poetry version
        run: echo "::set-output name=poetry-version::$(poetry --version | sed 's/[()]//g')"
        id: poetry-version

      - name: Cache additional repositories
        uses: actions/cache@v2
        id: repo-cache
        with:
          path: |
           tinker-engine
           Sail-On-API
           Sail_On_Evaluate
           sailon_tinker_launcher
          key: ${{ runner.os }}-repositories-${{ hashFiles('sail-on-client/poetry.lock') }}-${{ steps.poetry-version.outputs.poetry-version }}-${{ secrets.CACHE_VERSION }}-${{ matrix.python-version }}


      - name: Cache Poetry environment
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.local/share/poetry-virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('sail-on-client/poetry.lock') }}-${{ steps.poetry-version.outputs.poetry-version }}-${{ secrets.CACHE_VERSION }}-${{ matrix.python-version }}


      - name: Install Using Poetry
        run: poetry install --no-interaction -vvv
        working-directory: sail-on-client

      - name: Install Local Dependencies
        run: poetry run pip install ../tinker-engine ../sailon_tinker_launcher ../Sail-On-API/ ../Sail_On_Evaluate/
        working-directory: sail-on-client

  lint:
    needs: build
    name: Run linting on sail on client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sail on client
        uses: actions/checkout@v2
        with:
          path: sail-on-client
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.10'
          architecture: 'x64'

      - name: Install poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.local/share/poetry-virtualenvs
          version: 1.2.0a1

      - name: Capture poetry version
        run: echo "::set-output name=poetry-version::$(poetry --version | sed 's/[()]//g')"
        id: poetry-version

      - name: Cache additional repositories
        uses: actions/cache@v2
        with:
          path: |
           tinker-engine
           Sail-On-API
           Sail_On_Evaluate
           sailon_tinker_launcher
          key: ${{ runner.os }}-repositories-${{ hashFiles('sail-on-client/poetry.lock') }}-${{ steps.poetry-version.outputs.poetry-version }}-${{ secrets.CACHE_VERSION }}-3.7.10

      - name: Cache Pipenv environment
        id: poetry-cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/poetry-virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('sail-on-client/poetry.lock') }}-${{ steps.poetry-version.outputs.poetry-version }}-${{ secrets.CACHE_VERSION }}-3.7.10

      - name: Install Using Poetry
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install --no-interaction
        working-directory: sail-on-client

      - name: Install Local Dependencies
        run: poetry run pip install ../tinker-engine ../sailon_tinker_launcher ../Sail-On-API/ ../Sail_On_Evaluate/
        working-directory: sail-on-client

      - name: Run linting
        run: poetry run flake8
        working-directory: sail-on-client

  typecheck:
    needs: build
    name: Run typechecking on sail on client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sail on client
        uses: actions/checkout@v2
        with:
          path: sail-on-client
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.10'
          architecture: 'x64'

      - name: Install poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.local/share/poetry-virtualenvs
          version: 1.2.0a1

      - name: Capture poetry version
        run: echo "::set-output name=poetry-version::$(poetry --version | sed 's/[()]//g')"
        id: poetry-version

      - name: Cache additional repositories
        uses: actions/cache@v2
        with:
          path: |
           tinker-engine
           Sail-On-API
           Sail_On_Evaluate
           sailon_tinker_launcher
          key: ${{ runner.os }}-repositories-${{ hashFiles('sail-on-client/poetry.lock') }}-${{ steps.poetry-version.outputs.poetry-version }}-${{ secrets.CACHE_VERSION }}-3.7.10

      - name: Cache Poetry environment
        id: poetry-cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/poetry-virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('sail-on-client/poetry.lock') }}-${{ steps.poetry-version.outputs.poetry-version }}-${{ secrets.CACHE_VERSION }}-3.7.10

      - name: Install Using Poetry
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install --no-interaction
        working-directory: sail-on-client

      - name: Install Local Dependencies
        run: poetry run pip install ../tinker-engine ../sailon_tinker_launcher ../Sail-On-API/ ../Sail_On_Evaluate/
        working-directory: sail-on-client

      - name: Run typechecking
        run: poetry run mypy -p sail_on_client --disallow-untyped-defs
        working-directory: sail-on-client

  test-with-coverage:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7.10', '3.8.10', '3.9.5' ]
    name: Run test and generate coverage report on sail on client for python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sail on client
        uses: actions/checkout@v2
        with:
          path: sail-on-client
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.local/share/poetry-virtualenvs
          version: 1.2.0a1

      - name: Capture poetry version
        run: echo "::set-output name=poetry-version::$(poetry --version | sed 's/[()]//g')"
        id: poetry-version

      - name: Cache additional repositories
        uses: actions/cache@v2
        with:
          path: |
           tinker-engine
           Sail-On-API
           Sail_On_Evaluate
           sailon_tinker_launcher
          key: ${{ runner.os }}-repositories-${{ hashFiles('sail-on-client/poetry.lock') }}-${{ steps.poetry-version.outputs.poetry-version }}-${{ secrets.CACHE_VERSION }}-${{ matrix.python-version }}

      - name: Cache Poetry environment
        id: poetry-cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/poetry-virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('sail-on-client/poetry.lock') }}-${{ steps.poetry-version.outputs.poetry-version }}-${{ secrets.CACHE_VERSION }}-${{ matrix.python-version }}

      - name: Install Using Poetry
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install --no-interaction
        working-directory: sail-on-client

      - name: Install Local Dependencies
        run: poetry run pip install ../tinker-engine ../sailon_tinker_launcher ../Sail-On-API/ ../Sail_On_Evaluate/
        working-directory: sail-on-client

      - name: Explicitly activate particular environment
        run: poetry env use ${{ matrix.python-version }}
        working-directory: sail-on-client

      - name: Run Test with coverage
        run: poetry run coverage run --source=. -m pytest tests
        working-directory: sail-on-client

      - name: Generate coverage report
        run: |
          poetry run coverage report -m
          poetry run coverage xml
        working-directory: sail-on-client

      - name: Upload coverage report to code cov
        if: matrix.python-version == '3.7.10'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          files: ./sail-on-client/coverage.xml

  pages:
    needs: build
    name: Generate documentation and upload it on pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sail on client
        uses: actions/checkout@v2
        with:
          path: sail-on-client
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.10'
          architecture: 'x64'

      - name: Install poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.local/share/poetry-virtualenvs
          version: 1.2.0a1

      - name: Capture poetry version
        run: echo "::set-output name=poetry-version::$(poetry --version | sed 's/[()]//g')"
        id: poetry-version

      - name: Cache additional repositories
        uses: actions/cache@v2
        with:
          path: |
           tinker-engine
           Sail-On-API
           Sail_On_Evaluate
           sailon_tinker_launcher
          key: ${{ runner.os }}-repositories-${{ hashFiles('sail-on-client/poetry.lock') }}-${{ steps.poetry-version.outputs.poetry-version }}-${{ secrets.CACHE_VERSION }}-3.7.10

      - name: Cache poetry environment
        id: poetry-cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/poetry-virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('sail-on-client/poetry.lock') }}-${{ steps.poetry-version.outputs.poetry-version }}-${{ secrets.CACHE_VERSION }}-3.7.10

      - name: Install Using Poetry
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install --no-interaction
        working-directory: sail-on-client

      - name: Install Local Dependencies
        run: poetry run pip install ../tinker-engine ../sailon_tinker_launcher ../Sail-On-API/ ../Sail_On_Evaluate/
        working-directory: sail-on-client

      - name: Generate docs
        run: poetry run sphinx-build docs/source/ docs/build/html/
        working-directory: sail-on-client

      - name: Upload docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sail-on-client/docs/build/html

